### PR TITLE
Diagonal Traverse

### PR DESCRIPTION
**Pull request by h-asawa**

### CODE REVIEW

**Comment by h-asawa** [comment]
Add file of traverse Diagonally in TwoDArray for Upper Triangular Matrix #3

**Comment by h-asawa** [comment]
fixes issue #3

**Review by codea-holic — CHANGES_REQUESTED** [review]
Try to reduce it's time complexity from O(n^3) to O(n^2).

**Comment by h-asawa** [comment]
updated the complexity.
Also I have suggested changes for #4

**Review by codea-holic — APPROVED** [review]

**Pull request merged**
